# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Merge branch from develop
on:
  push:
    branches:
    - 'develop'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'develop'
      - name: Merge develop -> test
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: 'test'
          github_token: "${{ secrets.GITHUB_TOKEN }}"
